# <b>Fourth Stage: Data Configuration</b>

<div style='text-align: justify'>The final dataset generated in the previous step stores flux combinations in list format. Before proceeding to model analysis, the data must be restructured so that each enzyme has its own dedicated column.</div>

In [1]:
# Just pandas will be used for data manipulation
import pandas as pd

In [2]:
# Load the final dataset
df_naive = pd.read_csv('../Datasets/final_reunite.csv')
display(df_naive)

,Combination,NADH Production,Biomass
0,"[0.1737411608143376, 0.3813632293266472, 0.273...",7.699985,0.000000
1,"[0.0, 3.2375776324751, 0.2299188322402952, 2.5...",17.117679,0.066670
2,"[0.1737411608143376, 2.50454589036519, 0.26184...",7.950188,0.000000
3,"[0.521223482443013, 1.0740108707820433, 0.0, 1...",7.381223,0.000000
4,"[1.563670447329039, 1.0384824061453708, 0.4837...",18.814478,0.059855
...,...,...,...
999995,"[0.521223482443013, 0.6566962974349855, 0.3603...",8.340213,0.000000
999996,"[1.563670447329039, 2.871061761420145, 0.36131...",10.638736,0.000000
999997,"[0.521223482443013, 0.3054506640354609, 0.3603...",8.165782,0.000000
999998,"[1.2161881257003635, 0.8653535841085143, 0.145...",18.641485,0.000000
999999,"[1.2161881257003635, 1.9089328603427416, 1.252...",11.729880,0.000000

In [3]:
# List of reactions 
R_imp_final = ['PDH_fw','PPC_fw','CS_fw','ACONTa_fw','ACONTa_bw',
               'ACONTb_fw','ACONTb_bw','ICDHyr_fw','ICDHyr_bw',
               'AKGDH_fw','SUCOAS_fw','SUCOAS_bw','FUM_fw','FUM_bw',
               'FRD2_fw','ICL_fw','ICL_bw','MALS_fw']

In [4]:
# list_aux will store the combinations in float format, as they are currently in string format

list_aux = []
for i in df_naive['Combination']:
    replacements = str.maketrans({"[": "", "]": ""})
    res = i.translate(replacements)
    list_aux.append(res.split(','))

for i in range(len(list_aux)):
    for j in range(len(R_imp_final)):
        list_aux[i][j] = float(list_aux[i][j])

list_aux

[[0.1737411608143376,
  0.3813632293266472,
  0.2734014627111225,
  1.2522365629077563,
  0.9788351001966338,
  0.8155677442348392,
  0.5421662815237166,
  0.29474857344614636,
  0.2831890779409176,
  0.0,
  0.0,
  0.0,
  0.0,
  0.3698037338214186,
  0.3698037338214186,
  1.1619671647607333,
  0.9001251975548393,
  0.2618419672058939],
 [0.0,
  3.2375776324751,
  0.2299188322402952,
  2.5354500764001813,
  2.3055312441598863,
  1.7259697853989628,
  1.4960509531586679,
  1.3626751440039655,
  1.1327563117636703,
  0.0,
  0.9858462149332268,
  0.9508690059467552,
  1.1004654465119175,
  1.4792149352856745,
  0.4480390107614562,
  1.1619671647607333,
  1.1619671647607333,
  0.0],
 [0.1737411608143376,
  2.50454589036519,
  0.26184196720589314,
  2.0207469776277183,
  1.7589050104218251,
  2.43050709330076,
  2.1686651260948664,
  0.099470940827813,
  0.09947094082781316,
  0.0,
  0.4929231074666134,
  0.4929231074666134,
  0.3705282643807965,
  2.8750741547459873,
  2.5045458903651907,
  2.198453908473782,
  1.9366119412678884,
  0.2618419672058939],
 [0.521223482443013,
  1.0740108707820433,
  0.0,
  1.2522365629077563,
  1.2522365629077563,
  0.6416372223515296,
  0.6416372223515296,
  0.3826600187687306,
  0.38266001876873057,
  0.0,
  2.4375441970385534,
  2.4375441970385534,
  0.741056528761593,
  1.8150673995436364,
  1.0740108707820435,
  1.1619671647607333,
  1.1619671647607333,
  0.0],
 [1.563670447329039,
  1.0384824061453708,
  0.48372614818779425,
  1.2522365629077563,
  0.7685104147199621,
  3.736723837330094,
  3.2529976891423,
  1.2322272525914832,
  1.1681248299433846,
  0.0,
  0.031402229324280814,
  0.0,
  0.0,
  0.0,
  0.06220752090508279,
  1.9689132785540064,
  1.5492895530143107,
  0.41962372553969574],
 [0.521223482443013,
  3.604093503530055,
  0.0,
  1.2522365629077563,
  1.2522365629077563,
  3.3524686299701125,
  3.3524686299701125,
  0.6658490967096482,
  0.665849096709648,
  0.0,
  1.4787693223998402,
  1.47876932239984,
  0.0,
  1.4792149352856745,
  1.4792149352856745,
  2.3239343295214665,
  2.3239343295214665,
  0.0],
 [0.8687058040716883,
  1.404998277200325,
  0.48372614818779436,
  3.1735125997076614,
  2.689786451519867,
  0.48372614818779436,
  0.0,
  0.3826600187687306,
  0.3212065751570509,
  0.0614534436116797,
  2.9575386447996803,
  3.0189920884113595,
  0.3705282643807965,
  1.7140730979694419,
  1.3435448335886455,
  3.1335294223511583,
  2.7112567177750435,
  0.4222727045761147],
 [0.6949646432573506,
  3.2375776324751,
  0.099470940827813,
  0.4837261481877941,
  0.3842552073599811,
  2.26813606692268,
  2.168665126094867,
  0.3826600187687306,
  0.2831890779409174,
  0.09947094082781327,
  0.9858462149332268,
  1.08531715576104,
  0.0,
  1.4792149352856745,
  1.4792149352856745,
  0.7746447765071555,
  0.7746447765071555,
  0.0],
 [0.6949646432573506,
  3.2375776324751,
  0.4867933290813913,
  1.2522365629077563,
  0.765443233826365,
  1.5711258921288245,
  1.0843325630474332,
  2.3649835643551538,
  2.2655126235273406,
  0.0,
  2.4655063608284817,
  2.4375441970385534,
  0.0,
  0.0,
  0.0553927834406456,
  1.9366119412678888,
  1.5492895530143107,
  0.3873223882535781],
 [0.0,
  1.404998277200325,
  0.4908146150652595,
  0.4908146150652595,
  0.0,
  1.0329808965889762,
  0.5421662815237166,
  0.9699121152117969,
  0.5663781558818352,
  0.0614534436116797,
  3.450461752266293,
  3.4757922845319333,
  0.6792284474058949,
  1.4792149352856745,
  0.8715456354646806,
  2.411214985256764,
  2.323934329521466,
  0.0872806557352979],
 [1.3899292865147013,
  1.404998277200325,
  0.3307463093649193,
  2.2520223461648246,
  1.921276036799905,
  3.894634911493829,
  3.5638886021289093,
  0.3520934200999431,
  0.2831890779409176,
  0.0,
  0.521263413174676,
  0.4875088394077107,
  0.0,
  0.0,
  0.06686749311861831,
  1.4238091319666268,
  1.161967164760733,
  0.2618419672058939],
 [0.521223482443013,
  0.3054506640354609,
  0.2652347095236449,
  0.2652347095236449,
  0.0,
  0.2652347095236449,
  0.0,
  0.5484237874645626,
  0.2831890779409176,
  0.2458137744467191,
  1.4787693223998402,
  1.7150692496036004,
  1.12225933359294,
  1.109411201464256,
  0.005998709767237332,
  0.7746447765071555,
  0.7746447765071555,
  0.0],
 [1.2161881257003635,
  1.404998277200325,
  0.4038493541236047,
  1.556614976203548,
  1.1527656220799432,
  0.6416372223515296,
  0.23778786822792486,
  1.7986054084733183,
  1.4238496062614794,
  0.1843603308350393,
  2.9575386447996803,
  3.141898975634719,
  0.0,
  0.3698037338214186,
  0.3698037338214186,
  1.9657054931796543,
  1.9366119412678884,
  0.0290935519117659],
 [0.521223482443013,
  1.404998277200325,
  0.0,
  2.689786451519867,
  2.689786451519867,
  1.183803503875246,
  1.1838035038752461,
  0.6658490967096482,
  0.6658490967096484,
  0.0,
  0.4875088394077107,
  0.4875088394077107,
  2.5936978506655755,
  2.958429870571349,
  0.36473201990577353,
  0.0,
  0.0,
  0.0],
 [0.1737411608143376,
  1.404998277200325,
  0.1864362017694678,
  2.4050021849876995,
  2.2185659832182316,
  1.8129350463406175,
  1.6264988445711497,
  0.18643620176946785,
  0.0,
  0.0,
  0.04208141745794156,
  0.0,
  0.8171867402519585,
  1.4792149352856745,
  0.7453910871773702,
  1.549289553014311,
  1.549289553014311,
  0.0],
 [1.2161881257003635,
  1.0384824061453708,
  0.2299188322402952,
  1.3826844543202383,
  1.1527656220799432,
  0.2299188322402952,
  0.0,
  0.2299188322402952,
  0.0,
  0.04155922985566475,
  0.0,
  0.0,
  2.011861804251163,
  2.58862613674993,
  0.6590927759142905,
  0.7746447765071554,
  0.7746447765071554,
  0.0],
 [1.3899292865147013,
  0.6719665350904158,
  0.1864362017694678,
  0.4837261481877941,
  0.2972899464183263,
  0.6416372223515296,
  0.45520102058206185,
  0.4696252797103854,
  0.2831890779409176,
  0.18643620176946785,
  1.4787693223998402,
  1.6652055241693082,
  0.0,
  0.0,
  0.0,
  0.3873223882535777,
  0.3873223882535777,
  0.0],
 [1.563670447329039,
  3.2375776324751,
  0.37666768816412166,
  1.5294333102440647,
  1.1527656220799432,
  2.0031665327352712,
  1.6264988445711497,
  1.2322272525914832,
  1.1174015316332557,
  0.0614534436116797,
  1.971692429866453,
  2.007000083294879,
  0.3908738608186293,
  0.3698037338214186,
  0.0307244374143977,
  2.711256717775044,
  2.44941475056915,
  0.2618419672058939],
 [0.1737411608143376,
  2.147314715397063,
  0.4473319845944321,
  1.2522365629077563,
  0.8049045783133242,
  1.531664547641865,
  1.0843325630474332,
  0.7305210625353495,
  0.2831890779409176,
  0.0921801654175196,
  1.8578551922133233,
  1.950035357630843,
  0.741056528761593,
  2.4410392595642243,
  1.6999827308026314,
  1.549289553014311,
  1.549289553014311,
  0.0],
 [0.0,
  3.2375776324751,
  0.2734014627111225,
  0.4837261481877941,
  0.2103246854766716,
  0.815567744234839,
  0.5421662815237166,
  0.3826600187687306,
  0.33845071173414953,
  0.0,
  1.971692429866453,
  1.950035357630843,
  1.1386583523273779,
  1.109411201464256,
  0.01365530551750964,
  1.1619671647607333,
  0.932775009084192,
  0.22919215567654128],
 [1.2161881257003635,
  1.7715141482552803,
  0.099470940827813,
  0.4837261481877941,
  0.3842552073599811,
  0.09947094082781299,
  0.0,
  0.099470940827813,
  0.029093551911765908,
  0.0,
  1.0094938626270387,
  0.9750176788154216,
  2.5936978506655755,
  3.8080690122919267,
  1.282668157455573,
  0.0290935519117659,
  0.0,
  0.0290935519117659],
 [0.1737411608143376,
  1.0384824061453708,
  0.17968718330399308,
  0.17968718330399303,
  0.0,
  4.517017435493726,
  4.337330252189733,
  0.6658490967096482,
  0.5152554653174215,
  0.0614534436116797,
  0.0,
  0.01778581759915135,
  0.0,
  0.0,
  0.08650515636957196,
  1.1619671647607333,
  1.1328736128489674,
  0.0290935519117659],
 [0.8687058040716883,
  3.2375776324751,
  0.4603186781184748,
  1.2288290928384367,
  0.7685104147199621,
  1.5446512411659077,
  1.0843325630474332,
  0.6658490967096482,
  0.5928528068447515,
  0.0,
  0.9858462149332268,
  0.950087094771063,
  0.31489609802739826,
  1.109411201464256,
  0.8653535841085146,
  0.7746447765071555,
  0.3873223882535777,
  0.3873223882535778],
 [0.0,
  2.871061761420145,
  0.2299188322402952,
  1.2522365629077563,
  1.0223177306674611,
  2.398583958335162,
  2.1686651260948664,
  0.9490381746505656,
  0.8495672338227527,
  0.0,
  1.4787693223998402,
  1.4435428187902293,
  1.309616583488891,
  1.4792149352856745,
  0.239381724087927,
  1.549289553014311,
  1.4188416616018285,
  0.13044789141248248],
 [1.042446964886026,
  3.2375776324751,
  0.3168840931819499,
  0.3168840931819499,
  0.0,
  1.401216656229383,
  1.0843325630474332,
  1.4496404049456202,
  1.1327563117636703,
  0.0,
  0.4929231074666134,
  0.4576022236080109,
  0.8449781370016427,
  1.849018669107093,
  1.0740108707820435,
  2.3239343295214665,
  2.3239343295214665,
  0.0],
 [0.1737411608143376,
  2.50454589036519,
  0.029093551911765797,
  1.2522365629077563,
  1.2231430109959904,
  0.099470940827813,
  0.07037738891604714,
  0.099470940827813,
  0.099470940827813,
  0.0,
  1.4787693223998402,
  1.4787693223998402,
  0.31161662999788753,
  0.3698037338214186,
  0.058187103823531094,
  1.9657054931796543,
  1.9366119412678884,
  0.0290935519117659],
 [0.6949646432573506,
  3.2375776324751,
  0.5470272541080776,
  2.4050021849876995,
  1.8579749308796218,
  2.7156923802029445,
  2.1686651260948664,
  1.1134054099899133,
  0.5663781558818352,
  0.0,
  2.9250530364462644,
  2.9250530364462644,
  0.741056528761593,
  3.3282336043927674,
  2.5871770756311743,
  1.549289553014311,
  1.549289553014311,
  0.0],
 [0.0,
  1.7715141482552803,
  0.09947094082781316,
  1.2522365629077563,
  1.1527656220799432,
  4.978967474541262,
  4.879496533713449,
  1.515416330532401,
  1.4445832971357415,
  0.0,
  1.4972259112658433,
  1.4625265182231322,
  2.3487761089297727,
  2.58862613674993,
  0.3085891990365415,
  0.3873223882535777,
  0.3586844808224239,
  0.028637907431153686],
 [1.563670447329039,
  2.1380300193102357,
  0.09947094082781316,
  1.2522365629077563,
  1.1527656220799432,
  1.7259697853989628,
  1.6264988445711497,
  0.09947094082781316,
  0.0,
  0.0,
  1.4787693223998402,
  1.4420044186671415,
  0.0,
  0.7567311075227646,
  0.8295620359867054,
  2.3239343295214665,
  2.3239343295214665,
  0.0],
 [1.042446964886026,
  2.871061761420145,
  0.3603667236527773,
  1.1288771383727394,
  0.7685104147199621,
  0.36036672365277733,
  0.0,
  1.20993395747553,
  0.8495672338227527,
  0.0614534436116797,
  3.351108432242296,
  3.4125618758539757,
  0.0,
  0.6566962974349854,
  0.6566962974349854,
  0.3873223882535777,
  0.3873223882535777,
  0.0],
 [1.2161881257003635,
  3.2375776324751,
  0.4473319845944321,
  2.368608021394337,
  1.921276036799905,
  3.894634911493829,
  3.447302926899397,
  2.1464664522399373,
  1.6991344676455054,
  0.0,
  1.0005877613291756,
  0.9750176788154216,
  1.7739266455751597,
  2.58862613674993,
  0.8653535841085146,
  1.1619671647607333,
  1.1619671647607333,
  0.0],
 [1.2161881257003635,
  1.404998277200325,
  0.6416372223515303,
  1.0258924297115113,
  0.384255207359981,
  2.26813606692268,
  1.6264988445711497,
  1.2322272525914832,
  1.1652719081500775,
  0.0,
  0.520308646244615,
  0.4875088394077107,
  0.14788727901907678,
  0.7396074676428372,
  0.6566962974349854,
  1.34932665441728,
  0.7746447765071554,
  0.5746818779101247],
 [0.1737411608143376,
  2.50454589036519,
  0.3603667236527773,
  2.0207469776277183,
  1.660380253974941,
  3.6133644127950766,
  3.2529976891423,
  0.1843603308350393,
  0.0,
  0.1843603308350393,
  2.9575386447996803,
  3.1418989756347195,
  0.0,
  1.282668157455573,
  1.282668157455573,
  0.17600639281773747,
  0.0,
  0.17600639281773747],
 [0.6949646432573506,
  2.50454589036519,
  0.3603667236527773,
  3.1735125997076614,
  2.813145876054884,
  1.9868655682239265,
  1.6264988445711497,
  1.0062790940931676,
  0.8495672338227527,
  0.15671186027041495,
  2.9575386447996803,
  3.1142505050700953,
  0.0,
  1.0740108707820435,
  1.0740108707820435,
  0.9782996398895173,
  0.7746447765071554,
  0.2036548633823619],
 [0.3474823216286753,
  3.604093503530055,
  0.09947094082781316,
  0.09947094082781316,
  0.0,
  4.978967474541262,
  4.879496533713449,
  0.099470940827813,
  0.08728065573529786,
  0.012190285092515185,
  0.9858462149332268,
  0.998036500025742,
  0.0,
  0.0,
  0.0,
  2.0238925970031865,
  1.9366119412678884,
  0.0872806557352979],
 [1.2161881257003635,
  2.1380300193102357,
  0.3168840931819499,
  1.8539049226218738,
  1.537020829439924,
  2.485549219276816,
  2.1686651260948664,
  0.3826600187687306,
  0.06577592558678091,
  0.0,
  0.03874738823422632,
  0.0,
  0.9467876889894855,
  1.109411201464256,
  0.239381724087927,
  0.0,
  0.0,
  0.0],
 [0.521223482443013,
  0.3054506640354609,
  0.05818710382353193,
  0.8679813555477751,
  0.8097942517242431,
  1.183803503875246,
  1.125616400051714,
  0.3826600187687306,
  0.3826600187687306,
  0.0,
  1.9500353576308427,
  1.950035357630843,
  0.6232332599957755,
  0.7396074676428372,
  0.11637420764706174,
  0.44550949207710955,
  0.3873223882535777,
  0.0581871038235319],
 [0.6949646432573506,
  1.5995012859701374,
  0.4908146150652595,
  0.4908146150652595,
  0.0,
  3.7438123042075593,
  3.2529976891423,
  1.3403818488880122,
  0.8495672338227527,
  0.0307267218058398,
  1.431799796417292,
  1.4625265182231322,
  0.3705282643807965,
  1.4792149352856745,
  1.108686670904878,
  0.3873223882535777,
  0.3873223882535777,
  0.0],
 [0.8687058040716883,
  3.2375776324751,
  1.6364917702677373,
  2.0207469776277183,
  0.384255207359981,
  4.34732317788632,
  2.710831407618583,
  0.2150870526408792,
  0.0,
  0.2150870526408792,
  0.4929231074666134,
  0.7080101601074924,
  1.8526413219039823,
  2.58862613674993,
  0.7359848148459478,
  2.196049494134013,
  0.7746447765071554,
  1.4214047176268578],
 [0.6949646432573506,
  3.604093503530055,
  0.09947094082781316,
  2.78925739234768,
  2.689786451519867,
  3.3524686299701125,
  3.2529976891423,
  1.2322272525914832,
  1.1400470871739636,
  0.0921801654175196,
  0.4929231074666134,
  0.585103272884133,
  0.7612629085669109,
  1.109411201464256,
  0.34814829289734517,
  3.4859014942822,
  3.478610718871907,
  0.007290775410293104],
 [0.8687058040716883,
  0.4133844561831286,
  1.2522365629077563,
  2.0207469776277183,
  0.7685104147199621,
  2.878735407478906,
  1.6264988445711497,
  1.515416330532401,
  1.1327563117636703,
  0.1536336090291994,
  1.971692429866453,
  2.1253260388956523,
  1.482113057523186,
  1.5128374949375838,
  0.0307244374143977,
  2.0315437088997585,
  1.161967164760733,
  0.8695765441390255],
 [0.521223482443013,
  2.50454589036519,
  0.4038493541236047,
  1.556614976203548,
  1.1527656220799432,
  3.894634911493829,
  3.4907855573702236,
  0.20019449074124296,
  0.0,
  0.0,
  1.4967330079413694,
  1.4625265182231322,
  0.31182035172286593,
  1.109411201464256,
  0.8653535841085146,
  2.1402668046502504,
  1.9366119412678884,
  0.2036548633823619],
 [1.3899292865147013,
  3.2375776324751,
  0.09947094082781316,
  2.4050021849876995,
  2.3055312441598863,
  2.8103023484463963,
  2.710831407618583,
  1.2322272525914835,
  1.1327563117636703,
  0.0,
  1.4950812305680776,
  1.4625265182231322,
  0.09989090961032288,
  1.109411201464256,
  1.0740108707820435,
  0.3873223882535777,
  0.3873223882535777,
  0.0],
 [0.521223482443013,
  1.404998277200325,
  0.08526232490935516,
  1.636491770267737,
  1.551229445358382,
  4.436801193017546,
  4.351538868108191,
  0.368451402850273,
  0.2831890779409176,
  0.0,
  1.5042944728326346,
  1.4625265182231322,
  0.0,
  0.7396074676428372,
  0.8223493928323359,
  0.0,
  0.0,
  0.0],
 [0.6949646432573506,
  0.3054506640354609,
  0.40201948034339674,
  1.9390403097833206,
  1.537020829439924,
  1.183803503875246,
  0.781784023531849,
  0.285645272696333,
  0.0,
  0.276540496252559,
  1.971692429866453,
  2.2437727159425065,
  2.5936978506655755,
  2.58862613674993,
  0.00376392048886843,
  0.1163742076470639,
  0.0,
  0.1163742076470639],
 [1.2161881257003635,
  0.6719665350904158,
  0.1429535712986404,
  2.4050021849876995,
  2.262048613689059,
  0.6416372223515296,
  0.49868365105288937,
  0.099470940827813,
  0.099470940827813,
  0.0,
  1.9500353576308427,
  1.950035357630843,
  0.3705282643807965,
  1.042494799471212,
  0.6719665350904154,
  2.4668879008201063,
  2.323934329521466,
  0.14295357129864011],
 [1.563670447329039,
  3.604093503530055,
  0.2299188322402952,
  2.5354500764001813,
  2.3055312441598863,
  3.894634911493829,
  3.664716079253534,
  1.2322272525914832,
  1.047866921756444,
  0.1843603308350393,
  1.971692429866453,
  2.1560527607014923,
  0.0,
  0.0,
  0.0,
  0.3873223882535777,
  0.3417638868483217,
  0.04555850140525597],
 [0.6949646432573506,
  0.6719665350904158,
  0.48372614818779425,
  1.2522365629077563,
  0.7685104147199621,
  1.0258924297115108,
  0.5421662815237166,
  0.48372614818779425,
  0.0,
  0.1843603308350393,
  3.450461752266293,
  3.5987919604926386,
  1.5198658318402907,
  1.4792149352856745,
  0.0307244374143977,
  1.1619671647607333,
  1.1619671647607333,
  0.0],
 [1.2161881257003635,
  0.6719665350904158,
  0.09218016541751956,
  1.636491770267737,
  1.5443116048502175,
  1.7259697853989628,
  1.6337896199814432,
  0.3826600187687306,
  0.290479853351211,
  0.0921801654175196,
  0.9858462149332268,
  1.0780263803507462,
  0.3698037338214186,
  0.3698037338214186,
  0.0,
  0.7746447765071555,
  0.7746447765071555,
  0.0],
 [1.563670447329039,
  1.7715141482552803,
  0.26184196720589403,
  0.4837261481877941,
  0.2218841809819001,
  2.26813606692268,
  2.006294099716786,
  1.2322272525914832,
  1.2322272525914832,
  0.0,
  3.412561875853976,
  3.4125618758539757,
  0.3705282643807965,
  1.9341987117098356,
  1.563670447329039,
  2.3239343295214665,
  2.0620923623155725,
  0.2618419672058939],
 [0.6949646432573506,
  0.3054506640354609,
  0.1429535712986404,
  1.2522365629077563,
  1.109282991609116,
  0.14295357129864028,
  0.0,
  1.2322272525914832,
  1.2322272525914832,
  0.0,
  0.9858462149332268,
  0.9858462149332269,
  2.2831754727144693,
  2.58862613674993,
  0.3054506640354608,
  0.7746447765071555,
  0.6316912052085151,
  0.14295357129864028],
 [1.2161881257003635,
  0.8361802862331393,
  0.09947094082781316,
  2.0207469776277183,
  1.921276036799905,
  2.8103023484463963,
  2.710831407618583,
  0.3826600187687306,
  0.2831890779409174,
  0.09947094082781321,
  2.9575386447996803,
  3.057009585627493,
  1.482113057523186,
  2.218822402928512,
  0.7367093454053262,
  0.0,
  0.0,
  0.0],
 [0.8687058040716883,
  1.7715141482552803,
  0.3168840931819499,
  0.4837261481877941,
  0.1668420550058442,
  0.3168840931819499,
  0.0,
  2.299207638768373,
  1.982323545586423,
  0.1843603308350393,
  0.0,
  0.14720999818508898,
  0.6015969515356394,
  1.849018669107093,
  1.3210161770949274,
  2.7112567177750435,
  2.7112567177750435,
  0.0],
 [0.521223482443013,
  1.7715141482552803,
  0.12303248263281175,
  0.8679813555477751,
  0.7449488729149634,
  3.894634911493829,
  3.771602428861017,
  0.09393893072104564,
  0.0,
  0.09393893072104564,
  0.881078748094376,
  0.9750176788154216,
  1.482113057523186,
  2.0972754706872445,
  0.6151624131640585,
  2.353027881433232,
  2.323934329521466,
  0.0290935519117659],
 [0.521223482443013,
  1.7936100419958474,
  0.4038493541236047,
  0.4837261481877941,
  0.0798767940641894,
  2.5725144802184707,
  2.1686651260948664,
  1.4493250101519768,
  1.1327563117636703,
  0.1843603308350393,
  3.2282015450189365,
  3.4125618758539757,
  1.1115847931423894,
  2.58862613674993,
  1.4770413436075407,
  0.7746447765071555,
  0.6873641207718576,
  0.0872806557352979],
 [1.563670447329039,
  3.2375776324751,
  0.1864362017694678,
  0.4837261481877941,
  0.2972899464183263,
  2.8972676093880505,
  2.710831407618583,
  1.3191925135331377,
  1.1327563117636703,
  0.0,
  1.971692429866453,
  1.9414856681724137,
  1.8967474710384535,

In [5]:
"""Now, with the flux values converted to float format, a new data frame will be created containing only these values, excluding 
the biomass and NADH production columns.""" 

# The dictionary keys will be defined as numerical values, as this is more convenient for manipulation than using enzyme names.
dict_df = {k:[] for k in range(len(R_imp_final))}
for i in range(len(list_aux)):
    for j in range(len(list_aux[0])):
        dict_df[j].append(list_aux[i][j])

# The dictionary keys are reassigned to the corresponding enzyme names.
final_dict = dict(zip(R_imp_final, list(dict_df.values())))

# The data frame is created based on the previously constructed dictionary.
df_fluxes = pd.DataFrame(final_dict)
display(df_fluxes)

,PDH_fw,PPC_fw,CS_fw,ACONTa_fw,ACONTa_bw,ACONTb_fw,ACONTb_bw,ICDHyr_fw,ICDHyr_bw,AKGDH_fw,SUCOAS_fw,SUCOAS_bw,FUM_fw,FUM_bw,FRD2_fw,ICL_fw,ICL_bw,MALS_fw
0,0.173741,0.381363,0.273401,1.252237,0.978835,0.815568,0.542166,0.294749,0.283189,0.000000,0.000000,0.000000,0.000000,0.369804,0.369804,1.161967,0.900125,0.261842
1,0.000000,3.237578,0.229919,2.535450,2.305531,1.725970,1.496051,1.362675,1.132756,0.000000,0.985846,0.950869,1.100465,1.479215,0.448039,1.161967,1.161967,0.000000
2,0.173741,2.504546,0.261842,2.020747,1.758905,2.430507,2.168665,0.099471,0.099471,0.000000,0.492923,0.492923,0.370528,2.875074,2.504546,2.198454,1.936612,0.261842
3,0.521223,1.074011,0.000000,1.252237,1.252237,0.641637,0.641637,0.382660,0.382660,0.000000,2.437544,2.437544,0.741057,1.815067,1.074011,1.161967,1.161967,0.000000
4,1.563670,1.038482,0.483726,1.252237,0.768510,3.736724,3.252998,1.232227,1.168125,0.000000,0.031402,0.000000,0.000000,0.000000,0.062208,1.968913,1.549290,0.419624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.521223,0.656696,0.360367,1.636492,1.276125,0.360367,0.000000,1.515416,1.515416,0.000000,1.971692,1.971692,1.111585,1.768281,0.656696,3.071623,2.711257,0.360367
999996,1.563670,2.871062,0.361313,0.867981,0.506668,0.361313,0.000000,0.665849,0.566378,0.099471,3.943385,4.042856,0.000000,0.207693,0.207693,1.423809,1.161967,0.261842
999997,0.521223,0.305451,0.360367,2.789257,2.428891,1.444699,1.084333,2.480412,2.265513,0.000000,0.000000,0.000000,1.018860,1.109411,0.090552,2.082080,1.936612,0.145468
999998,1.216188,0.865354,0.145468,0.867981,0.722514,4.436801,4.291333,0.382660,0.382660,0.000000,3.412562,3.412562,0.000000,0.865354,0.865354,1.694757,1.549290,0.145468
999999,1.216188,1.908933,1.252237,1.636492,0.384255,1.252237,0.000000,1.252237,0.000000,0.000000,0.000000,0.000000,0.000000,0.656696,0.656696,0.000000,0.000000,0.000000

In [6]:
# The flux values must now be merged with the biomass and NADH columns.

# It is also necessary to convert the NADH and biomass values to float format, as they were stored as strings.
df_fluxes['NADH Production'] = df_naive['NADH Production'].apply(lambda x: float(x))
df_fluxes['Biomass'] = df_naive['Biomass'].apply(lambda x: float(x))

display(df_fluxes)

,PDH_fw,PPC_fw,CS_fw,ACONTa_fw,ACONTa_bw,ACONTb_fw,ACONTb_bw,ICDHyr_fw,ICDHyr_bw,AKGDH_fw,SUCOAS_fw,SUCOAS_bw,FUM_fw,FUM_bw,FRD2_fw,ICL_fw,ICL_bw,MALS_fw,NADH Production,Biomass
0,0.173741,0.381363,0.273401,1.252237,0.978835,0.815568,0.542166,0.294749,0.283189,0.000000,0.000000,0.000000,0.000000,0.369804,0.369804,1.161967,0.900125,0.261842,7.699985,0.000000
1,0.000000,3.237578,0.229919,2.535450,2.305531,1.725970,1.496051,1.362675,1.132756,0.000000,0.985846,0.950869,1.100465,1.479215,0.448039,1.161967,1.161967,0.000000,17.117679,0.066670
2,0.173741,2.504546,0.261842,2.020747,1.758905,2.430507,2.168665,0.099471,0.099471,0.000000,0.492923,0.492923,0.370528,2.875074,2.504546,2.198454,1.936612,0.261842,7.950188,0.000000
3,0.521223,1.074011,0.000000,1.252237,1.252237,0.641637,0.641637,0.382660,0.382660,0.000000,2.437544,2.437544,0.741057,1.815067,1.074011,1.161967,1.161967,0.000000,7.381223,0.000000
4,1.563670,1.038482,0.483726,1.252237,0.768510,3.736724,3.252998,1.232227,1.168125,0.000000,0.031402,0.000000,0.000000,0.000000,0.062208,1.968913,1.549290,0.419624,18.814478,0.059855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0.521223,0.656696,0.360367,1.636492,1.276125,0.360367,0.000000,1.515416,1.515416,0.000000,1.971692,1.971692,1.111585,1.768281,0.656696,3.071623,2.711257,0.360367,8.340213,0.000000
999996,1.563670,2.871062,0.361313,0.867981,0.506668,0.361313,0.000000,0.665849,0.566378,0.099471,3.943385,4.042856,0.000000,0.207693,0.207693,1.423809,1.161967,0.261842,10.638736,0.000000
999997,0.521223,0.305451,0.360367,2.789257,2.428891,1.444699,1.084333,2.480412,2.265513,0.000000,0.000000,0.000000,1.018860,1.109411,0.090552,2.082080,1.936612,0.145468,8.165782,0.000000
999998,1.216188,0.865354,0.145468,0.867981,0.722514,4.436801,4.291333,0.382660,0.382660,0.000000,3.412562,3.412562,0.000000,0.865354,0.865354,1.694757,1.549290,0.145468,18.641485,0.000000
999999,1.216188,1.908933,1.252237,1.636492,0.384255,1.252237,0.000000,1.252237,0.000000,0.000000,0.000000,0.000000,0.000000,0.656696,0.656696,0.000000,0.000000,0.000000,11.729880,0.000000

In [7]:
#df_fluxes.to_csv('../Datasets/Final_Data.csv',index=False)

<div style='text-align: justify'>With the dataset properly structured, the machine learning analysis can now proceed.</div><br>

# End of Part 4!